/**
 * Browsers and crawlers request /favicon.ico whether or not the page links to
 * one, and this site was answering that with a 404.
 *
 * The real icon is generated by `app/icon.tsx`, so rather than keep a second
 * copy in a different format that could drift out of sync, this points at it.
 * A permanent redirect is honest about what is happening — serving PNG bytes
 * under an `image/x-icon` content type would not be.
 *
 * The Location header is deliberately relative rather than built with
 * NextResponse.redirect(). This response is prerendered, and an absolute URL
 * would bake in whatever host the build ran on — which is localhost, not the
 * production domain.
 */
export const dynamic = "force-static";

export function GET() {
  return new Response(null, {
    status: 308,
    headers: {
      Location: "/icon",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
